# /etc/yt-dlp.conf

--js-runtimes @JS_RUNTIME@
#--embed-thumbnail
--embed-metadata
--paths temp:/tmp
--verbose

# Alpine specific fix:
#--postprocessor-args "ffmpeg:-threads 1"
--postprocessor-args "ThumbnailsConvertor:-threads 1"
